package woo.forsho.model;
// Generated 2017. 11. 13 ���� 9:20:52 by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usertable generated by hbm2java
 */
@Entity
@Table(name = "usertable", catalog = "forsho")
public class Usertable implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer key;
	private String name;
	private String id;
	private String password;
	private String tag1;
	private String tag2;
	private String tag3;

	public Usertable() {
	}

	public Usertable(String name, String id, String password, String tag1, String tag2, String tag3) {
		this.name = name;
		this.id = id;
		this.password = password;
		this.tag1 = tag1;
		this.tag2 = tag2;
		this.tag3 = tag3;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "key", unique = true, nullable = false)
	public Integer getKey() {
		return this.key;
	}

	public void setKey(Integer key) {
		this.key = key;
	}

	@Column(name = "name", nullable = false, length = 65535)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "id", nullable = false, length = 65535)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "password", nullable = false, length = 65535)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "tag1", nullable = false, length = 65535)
	public String getTag1() {
		return this.tag1;
	}

	public void setTag1(String tag1) {
		this.tag1 = tag1;
	}

	@Column(name = "tag2", nullable = false, length = 65535)
	public String getTag2() {
		return this.tag2;
	}

	public void setTag2(String tag2) {
		this.tag2 = tag2;
	}

	@Column(name = "tag3", nullable = false, length = 65535)
	public String getTag3() {
		return this.tag3;
	}

	public void setTag3(String tag3) {
		this.tag3 = tag3;
	}

}
